---
SERVICE_APP_NAME: jobflowexec
SERVICE_FACET: jobFlowExecution
SERVICE_INSTANCES_COUNT: '{{ play_hosts | length }}'
SERVICE_NAME: '{{ SERVICE_NAME_DEFAULT }}'
SERVICE_PRODUCT_NAME: jobflowexecution
SERVICE_SYSCONFIG_PATH: /etc/sysconfig/sas/{{ SERVICE_NAME }}
SERVICE_YUM_PACKAGE: sas-jobflowexecution
consumer_items:
  certificateAuthority-generateTokenForSecretsAndCertificates:
    APPNAME: jobflowexec
    DESTINATION_DIRECTORY: '{{ SAS_CONFIG_ROOT }}/etc/SASSecurityCertificateFramework/tokens/jobFlowExecution/{{
      INSTANCE_ID }}'
    DESTINATION_FILENAME: vault.token
    DESTINATION_GROUP: '{{ INSTALL_GROUP }}'
    DESTINATION_MODE: '0600'
    DESTINATION_OWNER: '{{ INSTALL_USER }}'
    DESTINATION_app.name: jobFlowExecution
    DESTINATION_destination.file.name: vault.token
