---
SERVICE_APP_NAME: evmcltsvcs
SERVICE_FACET: evmcltsvcs
SERVICE_INSTANCES_COUNT: '{{ play_hosts | length }}'
SERVICE_NAME: sas-{{ DEPLOYMENT_ID }}-alert-track-{{ INSTANCE_ID }}
SERVICE_PRODUCT_NAME: evmcltsvcs
SERVICE_SYSCONFIG_PATH: /etc/sysconfig/sas/{{ SERVICE_NAME }}
SERVICE_YUM_PACKAGE: sas-evmcltsvcs
consumer_items:
  certificateAuthority-generateTokenForSecretsAndCertificates-1.1:
    APPNAME: evmcltsvcs
    DESTINATION_DIRECTORY: '{{ SAS_CONFIG_ROOT }}/etc/SASSecurityCertificateFramework/tokens/evmcltsvcs/{{ INSTANCE_ID }}'
    DESTINATION_FILENAME: vault.token
    DESTINATION_GROUP: '{{ INSTALL_GROUP }}'
    DESTINATION_MODE: '0600'
    DESTINATION_OWNER: '{{ INSTALL_USER }}'
    DESTINATION_app.name: evmcltsvcs
    DESTINATION_destination.file.name: vault.token
