---
- block:
  - name: Determine certificate framework installations
    become: 'yes'
    become_user: root
    stat:
      path: "{{ item }}"
    register: certframe_install_paths
    with_items:
      - "{{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}"
      - "{{ SPRE_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}"

  - name: Verify the presence of a machine certificate
    become: 'yes'
    become_user: '{{ INSTALL_USER }}'
    register: cert
    stat: path='{{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}/private/sas_encrypted.key'
    when: inventory_hostname in COMBINED_GROUP

  - name: Create encryption password file
    become: 'yes'
    become_user: '{{ INSTALL_USER }}'
    file:
      path: "{{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}/private/encryption.key"
      owner: '{{ INSTALL_USER }}'
      group: '{{ INSTALL_GROUP }}'
      mode: 0600
      state: touch
    when: (inventory_hostname in COMBINED_GROUP) and (cert.stat.exists is defined and cert.stat.exists == false)

  - name: Generate random encryption password
    become: 'yes'
    become_user: '{{ INSTALL_USER }}'
    shell: '{{ SASHOME }}/SASSecurityCertificateFramework/bin/sas-crypto-management uuid --no-dashes > {{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}/private/encryption.key'
    when: (inventory_hostname in COMBINED_GROUP) and (cert.stat.exists is defined and cert.stat.exists == false)

  - name: Create certificate private key
    become: 'yes'
    become_user: '{{ INSTALL_USER }}'
    shell: 'cat {{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}/private/encryption.key | tr -d ''\n'' | {{ SASHOME }}/SASSecurityCertificateFramework/bin/sas-crypto-management genkey --out-file {{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}/private/sas_encrypted.key --out-form pem --passout ''-'' --cipher 3des'
    when: (inventory_hostname in COMBINED_GROUP) and (cert.stat.exists is defined and cert.stat.exists == false)

  - name: Grant world access on generated key
    become: 'yes'
    become_user: '{{ INSTALL_USER }}'
    file: path="{{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}/private/sas_encrypted.key" mode=0644
    when: (inventory_hostname in COMBINED_GROUP) and (cert.stat.exists is defined and cert.stat.exists == false)

  - name: Create certificate CSR file
    become: 'yes'
    become_user: '{{ INSTALL_USER }}'
    shell: 'cat {{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}/private/encryption.key | tr -d ''\n'' | {{ SASHOME }}/SASSecurityCertificateFramework/bin/sas-crypto-management gencsr --key {{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}/private/sas_encrypted.key --out-file {{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}/cacerts/sas_encrypted.csr --subject "C=US,O=Self-Signed Certificate,CN={{ hostvars[inventory_hostname].sas_vars.hostname_fqdn }}" --passout ''-'''
    when: (inventory_hostname in COMBINED_GROUP) and (cert.stat.exists is defined and cert.stat.exists == false)

  - name: Create certificate
    become: 'yes'
    become_user: '{{ INSTALL_USER }}'
    shell: 'cat {{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}/private/encryption.key | tr -d ''\n'' | {{ SASHOME }}/SASSecurityCertificateFramework/bin/sas-crypto-management selfsign --signing-key {{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}/private/sas_encrypted.key --csr {{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}/cacerts/sas_encrypted.csr --out-file {{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}/cacerts/sas_encrypted.crt --passout ''-'''
    when: (inventory_hostname in COMBINED_GROUP) and (cert.stat.exists is defined and cert.stat.exists == false)

  - name: Create certificate link
    become: 'yes'
    become_user: '{{ INSTALL_USER }}'
    file: src="{{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}/cacerts/sas_encrypted.crt" dest="{{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}/tls/certs/sas_encrypted.crt" state=link owner={{ INSTALL_USER }} group={{ INSTALL_GROUP }}
    when: (inventory_hostname in COMBINED_GROUP) and (cert.stat.exists is defined and cert.stat.exists == false)

  - name: Create temporary directory on Ansible machine
    local_action: shell mktemp -d
    run_once: yes
    register: tmpdir

  - name: Fetch certificates
    become: 'yes'
    become_user: '{{ INSTALL_USER }}'
    fetch: src="{{ SAS_CONFIG_ROOT }}/{{ CERTFRAME_REL_CONFIG_PATH }}/cacerts/sas_encrypted.crt" dest="{{ tmpdir.stdout }}/{{ inventory_hostname_short }}-ca-encrypted.crt" flat=yes fail_on_missing=yes
    when: (inventory_hostname in COMBINED_GROUP)

  - name: Distribute certificates
    become: 'yes'
    become_user: '{{ INSTALL_USER }}'
    copy: src="{{ tmpdir.stdout }}/" dest="{{ item.item }}/cacerts/"
    when: item.stat.exists | default(false)
    with_items: "{{ certframe_install_paths.results }}"

  - name: Update {{ SASHOME }} trust stores
    become: 'yes'
    become_user: '{{ INSTALL_USER }}'
    shell: '{{ SASHOME }}/SASSecurityCertificateFramework/bin/sas-merge-certificates.sh {{ SASHOME }} {{ SAS_CONFIG_ROOT }}'
    when: item.item == SAS_CONFIG_ROOT + '/' + CERTFRAME_REL_CONFIG_PATH and item.stat.exists | default(false)
    with_items: "{{ certframe_install_paths.results }}"

  - name: Update {{ SPREHOME }} trust stores
    become: 'yes'
    become_user: '{{ INSTALL_USER }}'
    shell: '{{ SPREHOME }}/SASSecurityCertificateFramework/bin/sas-merge-certificates.sh {{ SPREHOME }} {{ SPRE_CONFIG_ROOT }}'
    when: item.item == SPRE_CONFIG_ROOT + '/' + CERTFRAME_REL_CONFIG_PATH and item.stat.exists | default(false)
    with_items: "{{ certframe_install_paths.results }}"

  - name: Clean up temp folder on local machine
    delegate_to: 127.0.0.1
    file: path="{{ tmpdir.stdout }}" state=absent
    run_once: true
  when: not ansible_check_mode and COMBINED_GROUP | length > 0
