---
SERVICE_APP_NAME: foldersrvc
SERVICE_FACET: folders
SERVICE_INSTANCES_COUNT: '{{ play_hosts | length }}'
SERVICE_NAME: '{{ SERVICE_NAME_DEFAULT }}'
SERVICE_PRODUCT_NAME: folders
SERVICE_SYSCONFIG_PATH: /etc/sysconfig/sas/{{ SERVICE_NAME }}
SERVICE_YUM_PACKAGE: sas-folders
consumer_items:
  certificateAuthority-generateTokenForSecretsAndCertificates-1.1:
    APPNAME: foldersrvc
    DESTINATION_DIRECTORY: '{{ SAS_CONFIG_ROOT }}/etc/SASSecurityCertificateFramework/tokens/folders/{{ INSTANCE_ID }}'
    DESTINATION_FILENAME: vault.token
    DESTINATION_GROUP: '{{ INSTALL_GROUP }}'
    DESTINATION_MODE: '0600'
    DESTINATION_OWNER: '{{ INSTALL_USER }}'
    DESTINATION_app.name: folders
    DESTINATION_destination.file.name: vault.token
