---
- name: Get stats for {{ sasenv_license }}
  local_action: stat path="{{ sasenv_license }}"
  register: copy_file_1

- name: Copy from {{ sasenv_license }} to {{ SAS_CONFIG_ROOT }}/etc/licenses/setinit.txt
  become: 'yes'
  become_user: root
  copy: src="{{ sasenv_license }}" dest="{{ SAS_CONFIG_ROOT }}/etc/licenses/setinit.txt" owner={{ INSTALL_USER }} group={{ INSTALL_GROUP }} mode="0600"
  when: copy_file_1.stat.exists == true

- name: Get stats for {{ sasenv_composite_license }}
  local_action: stat path="{{ sasenv_composite_license }}"
  register: copy_file_2

- name: Copy from {{ sasenv_composite_license }} to {{ SAS_CONFIG_ROOT }}/etc/licenses/default
  become: 'yes'
  become_user: root
  copy: src="{{ sasenv_composite_license }}" dest="{{ SAS_CONFIG_ROOT }}/etc/licenses/default" owner={{ INSTALL_USER }} group={{ INSTALL_GROUP }} mode="0600"
  when: copy_file_2.stat.exists == true

- name: Get stats for {{ sasenv_composite_license }}
  local_action: stat path="{{ sasenv_composite_license }}"
  register: copy_file_3

- name: Copy from {{ sasenv_composite_license }} to {{ SAS_CONFIG_ROOT }}/etc/licenses/license.jwt
  become: 'yes'
  become_user: root
  copy: src="{{ sasenv_composite_license }}" dest="{{ SAS_CONFIG_ROOT }}/etc/licenses/license.jwt" owner={{ INSTALL_USER }} group={{ INSTALL_GROUP }} mode="0600"
  when: copy_file_3.stat.exists == true

- name: Get stats for {{ ENTITLEMENT_PATH }}
  local_action: stat path="{{ ENTITLEMENT_PATH }}"
  register: copy_file_4

- name: Confirm {{ ENTITLEMENT_PATH }} exists
  fail: msg="File '{{ ENTITLEMENT_PATH }}' not found"
  failed_when: copy_file_4.stat.exists == false

- name: Copy from {{ ENTITLEMENT_PATH }} to {{ SAS_CONFIG_ROOT }}/etc/pki/private/{{ METAREPO_CERT_CLIENT }}
  become: 'yes'
  become_user: root
  copy: src="{{ ENTITLEMENT_PATH }}" dest="{{ SAS_CONFIG_ROOT }}/etc/pki/private/{{ METAREPO_CERT_CLIENT }}" owner={{ INSTALL_USER }} group={{ INSTALL_GROUP }} mode="0600"
  when: copy_file_4.stat.exists == true

- name: Get stats for {{ SAS_CERT_PATH }}
  local_action: stat path="{{ SAS_CERT_PATH }}"
  register: copy_file_5

- name: Confirm {{ SAS_CERT_PATH }} exists
  fail: msg="File '{{ SAS_CERT_PATH }}' not found"
  failed_when: copy_file_5.stat.exists == false

- name: Copy from {{ SAS_CERT_PATH }} to {{ SAS_CONFIG_ROOT }}/etc/pki/certs/{{ METAREPO_CERT_CA }}
  become: 'yes'
  become_user: root
  copy: src="{{ SAS_CERT_PATH }}" dest="{{ SAS_CONFIG_ROOT }}/etc/pki/certs/{{ METAREPO_CERT_CA }}" owner={{ INSTALL_USER }} group={{ INSTALL_GROUP }} mode="0600"
  when: copy_file_5.stat.exists == true

