---
- name: Ensure sas-{{ DEPLOYMENT_ID }}-stream-evdm-{{ INSTANCE_ID }} service is started
  become: 'yes'
  become_user: root
  register: service_start
  service: name=sas-{{ DEPLOYMENT_ID }}-stream-evdm-{{ INSTANCE_ID }} state=started

- name: Ensure sas-{{ DEPLOYMENT_ID }}-ops-agentsrv-{{ INSTANCE_ID }} service is started
  become: 'yes'
  become_user: root
  register: service_start
  service: name=sas-{{ DEPLOYMENT_ID }}-ops-agentsrv-{{ INSTANCE_ID }} state=started

