---
# tasks file for foundation-validate

####################################################################################
## Make sure CAS host is defined
####################################################################################
- debug: var=sasenv_cas_host
  when: ( sas_deploy_debug | bool ) == true

- name: Set CAS host
  set_fact:
    controller_host: "{% if sasenv_cas_host is defined and sasenv_cas_host %}{{ sasenv_cas_host }}{%   elif groups['sas_casserver_primary'] | length > 0 %}{{ hostvars[groups['sas_casserver_primary'][0]]['sas_vars']['hostname_fqdn'] }}{%   else %}&SYSTCPIPHOSTNAME{%   endif %}"

- name: Assert that controller host is set
  fail:
    msg: "The host for the CAS controller is not known. Please set the sasenv_cas_host in the vars.yml file or define a controller host in the inventory file."
  failed_when: controller_host is defined and not controller_host
...