#ansible-playbook set_default_env_debian.yml --extra-var "target=es_prd_nk"
---
- hosts: '{{ target }}'
  tasks:
    - name: install packages
      apt:
        update_cache=yes
        state=latest
        name={{ item }}
      with_items:
        - vim
        - nano
        - htop

    - name: copie fichier de conf .bashrc
      copy:
        src=files/.bashrc
        dest=/root/.bashrc
        owner=root
        group=root

    - name: copie fichier de conf bash.bashrc
      copy:
        src=files/bash.bashrc
        dest=/etc/bash.bashrc
        owner=root
        group=root

    - name: copie fichier de conf vim
      copy:
        src=files/vimrc
        dest=/etc/vim/vimrc
        owner=root
        group=root
