---
############################################################################
## User Input Required
############################################################################
# The path and name of the sid file on the Ansible machine.
# This will be copied out to all nodes
sasenv_license: "{% if LICENSE_FILENAME | default ('') %}{{ orchestration_root|default(playbook_dir) }}/{{ LICENSE_FILENAME }}{% else %}Undefined{% endif %}"

# The path and name of the composite license file on the Ansible machine.
sasenv_composite_license: "{% if LICENSE_COMPOSITE_FILENAME | default ('') %}{{ orchestration_root|default(playbook_dir) }}/{{ LICENSE_COMPOSITE_FILENAME }}{% else %}Undefined{% endif %}"

############################################################################

# SAS METAREPO certificate details #
METAREPO_CERT_SOURCE: "{{ playbook_dir }}"
METAREPO_CERT_HOME: "/etc/pki/sas/private"
METAREPO_CERT_CA: SAS_CA_Certificate.pem
METAREPO_CERT_CLIENT: entitlement_certificate.pem
ENTITLEMENT_PATH: "{{ orchestration_root|default(playbook_dir) }}/{{ METAREPO_CERT_CLIENT }}"
SAS_CERT_PATH: "{{ orchestration_root|default(playbook_dir) }}/{{ METAREPO_CERT_CA }}"

# SAS METAREPO Install details #
METAREPO_INSTALL: "{{ REPOSITORY_WAREHOUSE == 'https://ses.sas.download/ses/' }}"
METAREPO_URL: "https://ses.sas.download/ses/repos/meta-repo/"
METAREPO_RPM: "sas-meta-repo.rpm"
METAREPO_SOE_ORDERABLE: '"sas-espcasvcf-100-x64_redhat_linux_6-yum" "sas-odbc-105-x64_redhat_linux_6-yum" "sas-txtminfre-105-x64_redhat_linux_6-yum" "sas-va-105-x64_redhat_linux_6-yum"'
METAREPO_FORCE_CERTS: "{{ REPOSITORY_WAREHOUSE == 'https://ses.sas.download/ses/' }}"

# Ordered software from the Software Order Email
sasenv_soe_groupinstall: '"SAS Data Connector to ODBC" "SAS Foundation for SAS Econometrics" "ASTORE for EMBSCOREENG" "Meta RPM Event Stream CAS Client" "SAS Foundation for SAS Visual Forecasting" "Gold Layer YUM Group for SPRE" "CUDA Library Support for SAS" "SAS Machine Learning" "SAS/ACCESS Interface to ODBC (SPRE)" "SAS Program Runtime Environment" "SAS Statistics" "SAS Text Analytics for French" "CAS for SAS Visual Analytics" "SAS Visual Text Analytics" "SAS Configuration for Spawner"'


SAS_REPO:
  espcasvcf-100-x64_redhat_linux_6-yum:
    name: espcasvcf-100-x64_redhat_linux_6-yum
    baseurl: '{{ REPOSITORY_WAREHOUSE }}repos/shipped/espcasvcf/100/espcasvcf-100-x64_redhat_linux_6-yum'
    enabled: 1
    gpgcheck: 0
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-SAS-9.x
    sslcacert: 0
    sslclientcert: 0
    sslverify: 0
  odbc-105-x64_redhat_linux_6-yum:
    name: odbc-105-x64_redhat_linux_6-yum
    baseurl: '{{ REPOSITORY_WAREHOUSE }}repos/shipped/odbc/105/odbc-105-x64_redhat_linux_6-yum'
    enabled: 1
    gpgcheck: 0
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-SAS-9.x
    sslcacert: 0
    sslclientcert: 0
    sslverify: 0
  txtminfre-105-x64_redhat_linux_6-yum:
    name: txtminfre-105-x64_redhat_linux_6-yum
    baseurl: '{{ REPOSITORY_WAREHOUSE }}repos/shipped/txtminfre/105/txtminfre-105-x64_redhat_linux_6-yum'
    enabled: 1
    gpgcheck: 0
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-SAS-9.x
    sslcacert: 0
    sslclientcert: 0
    sslverify: 0
  va-105-x64_redhat_linux_6-yum:
    name: va-105-x64_redhat_linux_6-yum
    baseurl: '{{ REPOSITORY_WAREHOUSE }}repos/shipped/va/105/va-105-x64_redhat_linux_6-yum'
    enabled: 1
    gpgcheck: 0
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-SAS-9.x
    sslcacert: 0
    sslclientcert: 0
    sslverify: 0
