---
- include: start-only.yml

# Start CAS services
- include: casserver-ensure-port-availability.yml
- include: cas.yml sas_task_file=start.yml

# Start SAS Foundation services
- include: foundation-ensure-port-availability.yml
- include: "{{ 'start-viya-foundation-services.yml' }}"
- include: "{{ 'services-foundation.yml' }} service_action=started"
