---
- name:  Copy and paste the Hadoop client files on the deployTarget hosts
  hosts: sas-casserver-primary:programming
  gather_facts: yes
  any_errors_fatal: true
  vars_files:
  - ../vars.yml

  roles:
    - hadooptracer-uploadclientfiles

