---
- name: scheduler on x64_redhat_linux_6-yum - configure.yml
  include_role:
    name: scheduler-x64_redhat_linux_6-yum
    tasks_from: configure.yml

- name: scheduler on x64_redhat_linux_6-yum - start.yml
  include_role:
    name: scheduler-x64_redhat_linux_6-yum
    tasks_from: start.yml

