---
- hosts: l-rec-nlb-01
  remote_user: root

  tasks:
    - name: Set server VPPPRNODEPR1 to disable state
      haproxy:
        state: disabled
        host: VPPPRNODEPR1
        socket: /tmp/haproxy.socket
        backend: VPPPRNODEPRx_http_ipvANY
        wait: yes
        # drain: yes
        wait_interval: 1
        wait_retries: 60
