---
# defaults file for foundation-validate

sas_studio_port: "{{ STUDIO_CONFIGURATION.init['sasstudio.appserver.port'] | default(7080) }}"
sas_studio_ssl_port: "{{ STUDIO_CONFIGURATION.init['sasstudio.appserver.https.port'] | default(7443) }}"
sas_spawner_port: "{{ SPAWNER_CONFIGURATION.sasPort | default(8591) }}"
sas_connect_port: "{{ sasenv_connect_port | default(17551) }}"
...