---
# common playbook

- name: common
  hosts: sas_all
  any_errors_fatal: true

  become_user: "{{ INSTALL_USER }}"

  vars_files:
    - ../vars.yml

  pre_tasks:
  - include_vars: "{{ item }}"
    with_first_found:
      - "{{ orchestration_root }}/soe.yml"
      - "{{ orchestration_root }}/internal/soe_defaults.yml"

  roles:
    - common

