---
- name: connect
  become_user: '{{ INSTALL_USER }}'
  hosts: programming:ComputeServer
  any_errors_fatal: true
  roles:
  - role: connect-config
    when: not ansible_check_mode
  vars_files:
  - ../vars.yml

...