---
# Verify host specification play

- name: Verify host specification
  hosts: sas_all

  become_user: "{{ INSTALL_USER }}"

  vars_files:
    - ../vars.yml

  pre_tasks:
  - include_vars: "{{ item }}"
    with_first_found:
      - "{{ orchestration_root }}/soe.yml"
      - "{{ orchestration_root }}/internal/soe_defaults.yml"

  roles:
    - host-verification
