---
# Lifecycle playbook

- name: Lifecycle
  hosts: sas_all[0]
  become_user: '{{ INSTALL_USER }}'
  any_errors_fatal: true
  vars_files:
    - ../vars.yml

  pre_tasks:
  - name: include soe.yml
    include_vars: '{{ item }}'
    with_first_found:
    - '{{ orchestration_root }}/soe.yml'
    - '{{ orchestration_root }}/internal/soe_defaults.yml'

  roles:
    - lifecycle
