---
# file: mt-programming.yml

- include: spawner.yml sas_task_file=conditional-stop.yml
- include: connect.yml sas_task_file=conditional-stop.yml

- name: "Object Spawner setup for tenant"
  hosts: programming
  any_errors_fatal: true
  gather_facts: false
  become: false

  vars:
    tenant_programming_conf: "{{ SASROOT }}/{{ DEPLOYMENT_ID }}/config/tenant_programming.conf"
    sas_tenant_instance: "{{ tenant_instance | default('default') }}"

  tasks:
    - name: Create file
      file:
        path: "{{ tenant_programming_conf }}"
        state: touch
        mode: "0664"
        owner: "{{ tenant_admin }}"
        group: "{{ tenant_admin_group }}"
      become: yes
      become_user: "{{ tenant_admin }}"

    - name: Add environment variables
      become: 'yes'
      become_user: "{{ tenant_admin }}"
      lineinfile:
        dest: "{{ tenant_programming_conf }}"
        regexp: "{{ item.regex }}"
        line: "{{ item.line}}"
      with_items:
        - { regex: "^\\s*export\\s+SASROOT\\s*=",             line: "export SASROOT='{{ SASROOT }}'" }
        - { regex: "^\\s*export\\s+SASINSTANCE\\s*=",         line: "export SASINSTANCE='{{ sas_tenant_instance }}'" }
        - { regex: "^\\s*export\\s+SASTENANT\\s*=",           line: "export SASTENANT='{{ sas_tenant }}'" }
        - { regex: "^\\s*export\\s+SASTENANTADMIN\\s*=",      line: "export SASTENANTADMIN='{{ tenant_admin }}'" }
        - { regex: "^\\s*export\\s+SASTENANTADMINGROUP\\s*=", line: "export SASTENANTADMINGROUP='{{ tenant_admin_group }}'" }
        - { regex: "^\\s*export\\s+SASTENANTUSERSGROUP\\s*=", line: "export SASTENANTUSERSGROUP='{{ tenant_users_group }}'" }

    - name: Run the script to create spawner and workspace pieces
      command: "{{ SASROOT }}/spre/home/bin/tenant_setup_spawner.sh --file {{ tenant_programming_conf }}"
      become: yes
      become_user: root

    - name: If CLUSTER_DEFINITIONS.cas is not empty, copy contents
      run_once: true
      set_fact:
        CLUSTER_DEFINITIONS_cas: "{{ CLUSTER_DEFINITIONS.cas }}"
      when: CLUSTER_DEFINITIONS.cas is defined and CLUSTER_DEFINITIONS.cas | string != 'None'

- include: spawner.yml
- include: connect.yml
...
