---
# file: mt-setup.yml

# This creates directories specific for a given tenant

- name: "Setup for tenant"
  hosts: ComputeServer:programming:sas_casserver*
  gather_facts: false
  become: false
  any_errors_fatal: true

  vars:
    tenant_setup_conf: "{{ SASROOT }}/{{ DEPLOYMENT_ID }}/config/tenant_setup.conf"

  tasks:
    - name: Create directory
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: "{{ tenant_admin }}"
        group: "{{ tenant_admin_group }}"
      become: yes
      become_user: root
      with_items:
        - "{{ SASROOT }}/{{ DEPLOYMENT_ID }}"
        - "{{ SASROOT }}/{{ DEPLOYMENT_ID }}/config"

    - name: Create file
      file:
        path: "{{ tenant_setup_conf }}"
        state: touch
        mode: "0664"
        owner: "{{ tenant_admin }}"
        group: "{{ tenant_admin_group }}"
      become: yes
      become_user: "{{ tenant_admin }}"

    - name: Add environment variables
      become: 'yes'
      become_user: "{{ tenant_admin }}"
      lineinfile:
        dest: "{{ tenant_setup_conf }}"
        regexp: "{{ item.regex }}"
        line: "{{ item.line}}"
      with_items:
        - { regex: "^\\s*export\\s+SASROOT\\s*=",             line: "export SASROOT='{{ SASROOT }}'" }
        - { regex: "^\\s*export\\s+SASTENANT\\s*=",           line: "export SASTENANT='{{ sas_tenant }}'" }
        - { regex: "^\\s*export\\s+SASTENANTADMIN\\s*=",      line: "export SASTENANTADMIN='{{ tenant_admin }}'" }
        - { regex: "^\\s*export\\s+SASTENANTADMINGROUP\\s*=", line: "export SASTENANTADMINGROUP='{{ tenant_admin_group }}'" }
        - { regex: "^\\s*export\\s+SASTENANTUSERSGROUP\\s*=", line: "export SASTENANTUSERSGROUP='{{ tenant_users_group }}'" }

    - name: Run the script to setup tenant directories
      command: '{{ SASROOT }}/viya/home/bin/tenant_setup.sh --file {{ tenant_setup_conf }}'
      become: yes
      become_user: root
...
