
---
# file: services-foundation.yml

###############################################################################
# Take action on the Viya Foundation services
- name: Manage the SAS Viya Foundation services
  hosts: programming
  any_errors_fatal: true
  gather_facts: no
  become: false

  vars:
    - sas_deployment_id: "{{ DEPLOYMENT_ID }}"
    - sas_consul_service: "{{ 'sas-' + sas_deployment_id | string + '-consul-' + INSTANCE_ID | string }}"

  vars_files:
    - ../vars.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - "{{ orchestration_root }}/soe.yml"
        - "{{ orchestration_root }}/internal/soe_defaults.yml"
  roles:
    - foundation_service_action: "{{ service_action }}"
      foundation_service_name: "{{ sas_consul_service }}"
      foundation_service_group: programming
      role: foundation-service
      when:
        - inventory_hostname not in groups['consul']
###############################################################################
...
