---
- name: mbagent on x64_redhat_linux_6-yum - configure-and-start
  include_role:
    name: mbagent-x64_redhat_linux_6-yum
    tasks_from: configure-and-start
  when: sas_task | default('start') == 'start'

- name: mbagent on x64_redhat_linux_6-yum - start
  include_role:
    name: mbagent-x64_redhat_linux_6-yum
    tasks_from: start
  when: sas_task | default('start') == 'start-only'

- name: mbagent on x64_redhat_linux_6-yum - stop
  include_role:
    name: mbagent-x64_redhat_linux_6-yum
    tasks_from: stop
  when: sas_task | default('start') == 'stop'

- name: mbagent on x64_redhat_linux_6-yum - apply-license
  include_role:
    name: mbagent-x64_redhat_linux_6-yum
    tasks_from: apply-license
  when: sas_task | default('start') == 'apply-license'

