---
SERVICE_APP_NAME: crossdmnprxy
SERVICE_FACET: crossdomainproxy
SERVICE_INSTANCES_COUNT: '{{ play_hosts | length }}'
SERVICE_NAME: '{{ SERVICE_NAME_DEFAULT }}'
SERVICE_PRODUCT_NAME: crossdomainproxy
SERVICE_SYSCONFIG_PATH: /etc/sysconfig/sas/{{ SERVICE_NAME }}
SERVICE_YUM_PACKAGE: sas-crossdomainproxy
consumer_items:
  certificateAuthority-generateTokenForSecretsAndCertificates-1.1:
    APPNAME: crossdmnprxy
    DESTINATION_DIRECTORY: '{{ SAS_CONFIG_ROOT }}/etc/SASSecurityCertificateFramework/tokens/crossdomainproxy/{{ INSTANCE_ID }}'
    DESTINATION_FILENAME: vault.token
    DESTINATION_GROUP: '{{ INSTALL_GROUP }}'
    DESTINATION_MODE: '0600'
    DESTINATION_OWNER: '{{ INSTALL_USER }}'
    DESTINATION_app.name: crossdomainproxy
    DESTINATION_destination.file.name: vault.token
